### ISSUE TITLE
TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by mFallW1nd** [Holit/Finger-Multi-threading#1]
dalao please help help me
![image](https://user-images.githubusercontent.com/87085697/194719189-36298216-6258-451a-83be-9d4538816f2e.png)

**Comment by Holit** [comment]
* Python 3 issue please manually modify `finger_plugin.py` at line 177:  
``` python
       # funcs = map(idaapi.getn_func, ctx.chooser_selection) # old
         funcs = list(idaapi.getn_func, ctx.chooser_selection)  # new
```

**Comment by shidalao** [comment]
> * Python 3 issue please manually modify `finger_plugin.py` at line 177:
> 
> ```python
>        # funcs = map(idaapi.getn_func, ctx.chooser_selection) # old
>          funcs = list(idaapi.getn_func, ctx.chooser_selection)  # new
> ```

Then it should be another error like this:
`    funcs = list(idaapi.getn_func, ctx.chooser_selection)
TypeError: list expected at most 1 argument, got 2`
