### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by mFallW1nd** [Holit/Finger-Multi-threading#2]
WE NEED PYTHON3 SUPPORT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Holit** [comment]
Still working on python 3, 
* Python 3 issue please manually modify `finger_plugin.py` at line 177:  
``` python
       # funcs = map(idaapi.getn_func, ctx.chooser_selection) # old
         funcs = list(idaapi.getn_func, ctx.chooser_selection)  # new
```
