### ISSUE TITLE
ida 7.7 error

### ISSUE THREAD

**Issue by ltlly** [Holit/Finger-Multi-threading#3]
I use ida7.7 and when I lanuch ida ,an error occurred!
![GVM{564A{I32)MR1UG@54HS](https://user-images.githubusercontent.com/86669384/196682293-a2be0439-4c0f-4555-818a-4a29fb2a8c8d.png)

**Comment by Holit** [comment]
repairing

**Comment by Holit** [comment]
forget it, I gave up.
> Reapir in future.

**Comment by Holit** [comment]
See commit 4ab2e58, may solved the 2028 issue.
Not tested yet.
